ignore all pdf files
cs-24-sw-3-01/typst-documents pull request #62
Opened 2024-10-17 08:25 UTC by Many5900

2024-10-18 08:38 UTC, tbdlarsen requested changes

2024-10-18 08:38 UTC, tbdlarsen commented on .gitignore
>  report/styleguide.pdf
```suggestion
```

2024-10-18 08:38 UTC, tbdlarsen commented on .gitignore
>  report/styleguide.pdf
these are invalid

2024-10-18 08:39 UTC, tbdlarsen approved these changes
LOKGOTTOME

2024-10-18 09:01 UTC, elmavukicevic approved these changes
make twiter apology

2024-10-22 07:54 UTC, glund23student approved these changes

2024-10-22 07:54 UTC, merged