event table explanation
cs-24-sw-3-01/typst-documents pull request #63
Opened 2024-10-17 08:44 UTC by Many5900

2024-10-18 08:35 UTC, tbdlarsen approved these changes

2024-10-18 08:36 UTC, tbdlarsen approved these changes
LGTM !

2024-10-18 09:05 UTC, elmavukicevic approved these changes
ok

2024-10-18 09:46 UTC, elmavukicevic requested changes
+ Rewrite "Team Update" to include Admin Update and Name Updated etc. 

+ Og
 at
alle events skal ændres fra x til + eller *. * hvis event er gentagende og + hvis en gang
så creation og deletion er + f.eks. og change admin, add employee etc. er *


+ Tilføje en ekstra klasse "Admin"

2024-10-22 07:55 UTC, glund23student approved these changes

2024-10-23 07:07 UTC, closed without merging