Update introduction.typ
cs-24-sw-3-01/typst-documents pull request #65
Opened 2024-10-17 15:15 UTC by elmavukicevic

Corrected introduction to remove " it's " etc. And to add that it should cost 0 kr.

Current VC section rewritten as discussed in group. Less opinions/problems, more redegørende.

Added section of pre-meeting as suggested by Sille where opinions were added instead

2024-10-18 06:07 UTC, Many5900 requested changes
Få enkelte kommentar, ellers synes jeg det ser meget godt ud!💪

2024-10-18 06:07 UTC, Many5900 commented on report/chapters/introduction.typ
> +The aim of this project is to develop a functional application that prioritizes user experience and meets the client’s needs. The primary requirement for this system is to develop a vacation planner
Ikke enig i at it's skal være it is, ser personlig ingen grund til at udvide mere end nødvendigt.

2024-10-18 06:07 UTC, Many5900 commented on report/chapters/introduction.typ
> +During the initial meeting with KMD representatives Dion and Mats, valuable context for understanding KMDFerieplan’s limitations for solution planning was provided. It was noted that KMDFerieplan was
Synes den første sætning er lidt "kavt"

2024-10-18 06:07 UTC, Many5900 commented on report/chapters/introduction.typ
> +During the initial meeting with KMD representatives Dion and Mats, valuable context for understanding KMDFerieplan’s limitations for solution planning was provided. It was noted that KMDFerieplan was
Husker det ikke som at det var synkronisering med "Microsoft Office Calendar", men en anden version af SAP, som de så opgraderede til "SAP S/4HANA" og derfor mistede synkronisering da det er en anden API.

2024-10-18 08:33 UTC, Many5900 approved these changes
LGTM!👾

2024-10-22 07:58 UTC, glund23student approved these changes

2024-10-22 08:54 UTC, merged